<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5BF502C" failures="1" tests="3" name="Error Validation Test" time="44.025" errors="0" timestamp="2024-06-10T15:25:54 CST">
  <testcase classname="devenik.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.9"/>
  <testcase classname="devenik.Tests.ErrorValidationsTest" name="productErrorValidation" time="6.813"/>
  <testcase classname="devenik.Tests.ErrorValidationsTest" name="productErrorValidation" time="16.666">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at devenik.Tests.ErrorValidationsTest.productErrorValidation(ErrorValidationsTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validation Test -->
